include ../makefile.conf
MAKE:$(patsubst %.c,%.o,$(wildcard *.c))
	@echo "stdio completed"

allocfil.o: allocfil.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/string.h ../include/stdlib.h \
  ../include/libc/file.h ../include/libc/local.h \
  ../include/libc/stdiohk.h
clearerr.o: clearerr.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
doprnt.o: doprnt.c ../include/libc/stubs.h ../include/sys/types.h \
  ../include/stdarg.h ../include/stdio.h ../include/sys/version.h \
  ../include/ctype.h ../include/locale.h ../include/stdlib.h \
  ../include/string.h ../include/math.h ../include/libc/file.h \
  ../include/libc/stdiohk.h ../include/libc/local.h
doscan.o: doscan.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdlib.h ../include/ctype.h \
  ../include/libc/file.h ../include/libc/local.h
fclose.o: fclose.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/file.h ../include/os/kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
fdopen.o: fdopen.c ../include/libc/stubs.h ../include/sys/types.h \
  ../include/stdio.h ../include/sys/version.h ../include/libc/file.h \
  ../include/libc/local.h ../include/os/kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
feof.o: feof.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
ferror.o: ferror.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
fflush.o: fflush.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/errno.h \
  ../include/stdlib.h ../include/libc/file.h ../include/os/Kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
fgetc.o: fgetc.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
fgetpos.o: fgetpos.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/errno.h
fgets.o: fgets.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
filbuf.o: filbuf.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/stdlib.h \
  ../include/string.h ../include/libc/file.h ../include/libc/stdiohk.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
flsbuf.o: flsbuf.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/file.h ../include/os/Kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
fopen.o: fopen.c ../include/libc/stubs.h ../include/sys/types.h \
  ../include/stdio.h ../include/sys/version.h ../include/stdlib.h \
  ../include/libc/file.h ../include/libc/local.h ../include/os/Kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
fprintf.o: fprintf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
fputc.o: fputc.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
fputs.o: fputs.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
fread.o: fread.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/stdlib.h \
  ../include/string.h ../include/libc/file.h
freopen.o: freopen.c ../include/libc/stubs.h ../include/sys/types.h \
  ../include/stdio.h ../include/sys/version.h ../include/libc/file.h
frlist.o: frlist.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/local.h
fscanf.o: fscanf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdarg.h ../include/libc/file.h
fseek.o: fseek.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/libc/file.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
fsetpos.o: fsetpos.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/errno.h
ftell.o: ftell.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/libc/file.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
fwalk.o: fwalk.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/local.h
fwrite.o: fwrite.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdlib.h ../include/string.h \
  ../include/libc/file.h
getc.o: getc.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
getchar.o: getchar.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
gets.o: gets.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h
getw.o: getw.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
perror.o: perror.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/string.h ../include/errno.h
printf.o: printf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
putc.o: putc.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
putchar.o: putchar.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
puts.o: puts.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h
putw.o: putw.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
pwerror.o: pwerror.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/string.h ../include/wchar.h \
  ../include/errno.h
remove.o: remove.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/errno.h
rename.o: rename.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/errno.h
rewind.o: rewind.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/libc/file.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
scanf.o: scanf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdarg.h ../include/libc/file.h
setbuf.o: setbuf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdlib.h ../include/libc/file.h
setbuffe.o: setbuffe.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/stdlib.h
setlineb.o: setlineb.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h
setvbuf.o: setvbuf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdlib.h ../include/libc/file.h
sprintf.o: sprintf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/limits.h ../include/libc/file.h
sscanf.o: sscanf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdarg.h ../include/libc/file.h \
  ../include/libc/unconst.h
stdaux.o: stdaux.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/stdiohk.h
stderr.o: stderr.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/stdiohk.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
stdin.o: stdin.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/stdiohk.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
stdio.o: stdio.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
stdiohk.o: stdiohk.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/local.h
stdout.o: stdout.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/stdiohk.h \
  ../include/os/Kernel32.h ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
stdprn.o: stdprn.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h ../include/libc/stdiohk.h
tmpfile.o: tmpfile.c ../include/libc/stubs.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/string.h \
  ../include/stdlib.h ../include/errno.h ../include/libc/file.h \
  ../include/libc/local.h ../include/os/Kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
tmpnam.o: tmpnam.c ../include/libc/stubs.h ../include/string.h \
  ../include/sys/types.h ../include/stdlib.h ../include/stdio.h \
  ../include/sys/version.h ../include/errno.h ../include/os/Kernel32.h \
  ../../Kernel32.dll/Include/Kernel32.h \
  ../../Kernel32.dll/Include/TypeDefs.h
ungetc.o: ungetc.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/libc/file.h
vfprintf.o: vfprintf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdarg.h ../include/libc/file.h
vprintf.o: vprintf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdarg.h ../include/libc/file.h
vsprintf.o: vsprintf.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/stdarg.h ../include/limits.h \
  ../include/libc/file.h
