include ../makefile.conf
MAKE:$(patsubst %.c,%.o,$(wildcard *.c))
	@echo "stdlib completed"

abort.o: abort.c ../include/stdlib.h ../include/sys/types.h
abs.o: abs.c ../include/stdlib.h ../include/sys/types.h
atexit.o: atexit.c ../include/stdlib.h ../include/sys/types.h \
  ../include/libc/atexit.h
atof.o: atof.c ../include/stdlib.h ../include/sys/types.h
atoi.o: atoi.c ../include/stdlib.h ../include/sys/types.h
atol.o: atol.c ../include/stdlib.h ../include/sys/types.h
atold.o: atold.c ../include/stdlib.h ../include/sys/types.h
bsdqsort.o: bsdqsort.c ../include/stdlib.h ../include/sys/types.h
bsearch.o: bsearch.c ../include/stdlib.h ../include/sys/types.h \
  ../include/libc/unconst.h
div.o: div.c ../include/stdlib.h ../include/sys/types.h
exit.o: exit.c ../include/libc/stubs.h ../include/stdlib.h \
  ../include/sys/types.h ../include/libc/atexit.h
labs.o: labs.c ../include/stdlib.h ../include/sys/types.h
ldiv.o: ldiv.c ../include/stdlib.h ../include/sys/types.h
llabs.o: llabs.c ../include/stdlib.h ../include/sys/types.h
lldiv.o: lldiv.c ../include/stdlib.h ../include/sys/types.h
maldebug.o: maldebug.c ../include/malloc.h ../include/sys/types.h \
  ../include/stdlib.h ../include/assert.h ../include/string.h \
  ../include/wchar.h ../include/stdio.h ../include/sys/version.h
malloc.o: malloc.c ../include/stddef.h ../include/stdio.h \
  ../include/sys/version.h ../include/errno.h
mallock.o: mallock.c ../include/malloc.h ../include/sys/types.h
#malwrap.o: malwrap.c ../include/malloc.h ../include/sys/types.h
mbtowc.o: mbtowc.c ../include/stdlib.h ../include/sys/types.h
qsort.o: qsort.c ../include/assert.h ../include/stdio.h \
  ../include/sys/version.h ../include/sys/types.h ../include/stdlib.h
rand.o: rand.c ../include/stdlib.h ../include/sys/types.h
strtod.o: strtod.c ../include/math.h ../include/stdlib.h \
  ../include/sys/types.h ../include/float.h ../include/errno.h \
  ../include/libc/unconst.h
strtol.o: strtol.c ../include/limits.h ../include/ctype.h \
  ../include/errno.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/unconst.h
strtold.o: strtold.c ../include/stdlib.h ../include/sys/types.h \
  ../include/ctype.h ../include/libc/unconst.h
strtoll.o: strtoll.c ../include/limits.h ../include/ctype.h \
  ../include/errno.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/unconst.h
strtoul.o: strtoul.c ../include/limits.h ../include/ctype.h \
  ../include/errno.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/unconst.h
strtoull.o: strtoull.c ../include/limits.h ../include/ctype.h \
  ../include/errno.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/unconst.h
wcstol.o: wcstol.c ../include/limits.h ../include/wchar.h \
  ../include/sys/types.h ../include/errno.h ../include/stdlib.h \
  ../include/libc/unconst.h
wcstoul.o: wcstoul.c ../include/limits.h ../include/ctype.h \
  ../include/errno.h ../include/sys/types.h ../include/stdlib.h \
  ../include/libc/unconst.h ../include/wchar.h
wctomb.o: wctomb.c ../include/stdlib.h ../include/sys/types.h
