include ../makefile.conf
MAKE:$(patsubst %.c,%.o,$(wildcard *.c))
	@echo "math completed"
acos.o: acos.c ../include/math.h
acosh.o: acosh.c ../include/math.h
asin.o: asin.c ../include/math.h
asinh.o: asinh.c ../include/math.h
atan.o: atan.c
atan2.o: atan2.c
atanh.o: atanh.c ../include/math.h
ceil.o: ceil.c ../include/math.h
cos.o: cos.c
cosh.o: cosh.c ../include/math.h
exp.o: exp.c
fabs.o: fabs.c
floor.o: floor.c
fmod.o: fmod.c
frexp.o: frexp.c ../include/math.h ../include/stdlib.h \
  ../include/sys/types.h ../include/internal.h
ftol.o: ftol.c ../include/float.h
hypot.o: hypot.c ../include/float.h ../include/math.h ../include/errno.h \
  ../include/sys/types.h
isnan.o: isnan.c ../include/math.h ../include/float.h \
  ../include/internal.h
j0_y0.o: j0_y0.c ../include/math.h
j1_y1.o: j1_y1.c ../include/math.h
jn_yn.o: jn_yn.c ../include/math.h
ldexp.o: ldexp.c
log.o: log.c
log10.o: log10.c
modf.o: modf.c ../include/float.h ../include/math.h ../include/internal.h
pow.o: pow.c
sin.o: sin.c
sinh.o: sinh.c ../include/math.h
sqrt.o: sqrt.c
tan.o: tan.c
tanh.o: tanh.c ../include/math.h
