include ../makefile.conf
MAKE:$(patsubst %.c,%.o,$(wildcard *.c))
	@echo "ctype completed"
ct_flags.o: ct_flags.c ../include/ctype.h ../include/inlines/ctype.ha
ct_lower.o: ct_lower.c ../include/ctype.h ../include/inlines/ctype.ha
ct_upper.o: ct_upper.c ../include/ctype.h ../include/inlines/ctype.ha
isalnum.o: isalnum.c ../include/ctype.h ../include/inlines/ctype.ha
isalpha.o: isalpha.c ../include/ctype.h ../include/inlines/ctype.ha
isascii.o: isascii.c ../include/ctype.h ../include/inlines/ctype.ha
iscntrl.o: iscntrl.c ../include/ctype.h ../include/inlines/ctype.ha
isdigit.o: isdigit.c ../include/ctype.h ../include/inlines/ctype.ha
isgraph.o: isgraph.c ../include/ctype.h ../include/inlines/ctype.ha
islower.o: islower.c ../include/ctype.h ../include/inlines/ctype.ha
isprint.o: isprint.c ../include/ctype.h ../include/inlines/ctype.ha
ispunct.o: ispunct.c ../include/ctype.h ../include/inlines/ctype.ha
isspace.o: isspace.c ../include/ctype.h ../include/inlines/ctype.ha
isupper.o: isupper.c ../include/ctype.h ../include/inlines/ctype.ha
iswlower.o: iswlower.c ../include/wchar.h ../include/sys/types.h
iswupper.o: iswupper.c ../include/wchar.h ../include/sys/types.h
isxdigit.o: isxdigit.c ../include/ctype.h ../include/inlines/ctype.ha
toascii.o: toascii.c ../include/ctype.h ../include/inlines/ctype.ha
tolower.o: tolower.c ../include/ctype.h ../include/inlines/ctype.ha
toupper.o: toupper.c ../include/ctype.h ../include/inlines/ctype.ha
towlower.o: towlower.c ../include/ctype.h ../include/wchar.h \
  ../include/sys/types.h
towupper.o: towupper.c ../include/ctype.h ../include/wchar.h \
  ../include/sys/types.h
unicode.o: unicode.c ../include/wchar.h ../include/sys/types.h
