include ../makefile.conf
MAKE:$(patsubst %.c,%.o,$(wildcard *.c))
	@echo "time completed"

localtime.o: localtime.c ../include/time.h ../include/sys/types.h
time.o: time.c ../include/time.h ../include/sys/types.h
