include ../makefile.conf
MAKE:$(patsubst %.c,%.o,$(wildcard *.c)) $(patsubst %.S,%.o,$(wildcard *.S))
	@echo "string completed"

mbstowcs.o: mbstowcs.c ../include/wchar.h ../include/sys/types.h \
  ../include/errno.h
memchr.o: memchr.c ../include/string.h ../include/sys/types.h
memcmp.o: memcmp.c ../include/string.h ../include/sys/types.h
strcat.o: strcat.c ../include/string.h ../include/sys/types.h
strchr.o: strchr.c ../include/string.h ../include/sys/types.h
strcmp.o: strcmp.c ../include/string.h ../include/sys/types.h
strcoll.o: strcoll.c ../include/string.h ../include/sys/types.h
strcpy.o: strcpy.c ../include/string.h ../include/sys/types.h
strcspn.o: strcspn.c ../include/string.h ../include/sys/types.h
strdup.o: strdup.c ../include/string.h ../include/sys/types.h \
  ../include/stdlib.h
strerror.o: strerror.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/string.h ../include/errno.h
stricmp.o: stricmp.c ../include/string.h ../include/sys/types.h \
  ../include/ctype.h
strlen.o: strlen.c ../include/string.h ../include/sys/types.h
strncat.o: strncat.c ../include/string.h ../include/sys/types.h
strncmp.o: strncmp.c ../include/string.h ../include/sys/types.h
strncpy.o: strncpy.c ../include/string.h ../include/sys/types.h
strpbrk.o: strpbrk.c ../include/string.h ../include/sys/types.h
strrchr.o: strrchr.c ../include/string.h ../include/sys/types.h
strspn.o: strspn.c ../include/string.h ../include/sys/types.h
strstr.o: strstr.c ../include/string.h ../include/sys/types.h
strtok.o: strtok.c ../include/string.h ../include/sys/types.h
strxfrm.o: strxfrm.c ../include/string.h ../include/sys/types.h
syserr1.o: syserr1.c syserr1.h
syserr2.o: syserr2.c ../include/errno.h ../include/sys/types.h syserr1.h
syserr3.o: syserr3.c ../include/errno.h ../include/sys/types.h syserr1.h
syswerr1.o: syswerr1.c ../include/wchar.h ../include/sys/types.h \
  syserr1.h
syswerr2.o: syswerr2.c ../include/wchar.h ../include/sys/types.h \
  ../include/errno.h syserr1.h
syswerr3.o: syswerr3.c ../include/wchar.h ../include/sys/types.h \
  ../include/errno.h syserr1.h
wcscat.o: wcscat.c ../include/string.h ../include/sys/types.h
wcschr.o: wcschr.c ../include/string.h ../include/sys/types.h
wcscmp.o: wcscmp.c ../include/string.h ../include/sys/types.h
wcscpy.o: wcscpy.c ../include/string.h ../include/sys/types.h
wcsdup.o: wcsdup.c ../include/wchar.h ../include/sys/types.h \
  ../include/stdlib.h
wcserror.o: wcserror.c ../include/stdio.h ../include/sys/version.h \
  ../include/sys/types.h ../include/wchar.h ../include/errno.h
wcsicmp.o: wcsicmp.c ../include/wchar.h ../include/sys/types.h
wcslen.o: wcslen.c ../include/wchar.h ../include/sys/types.h
wcsmatch.o: wcsmatch.c ../include/ctype.h ../include/wchar.h \
  ../include/sys/types.h
wcsncmp.o: wcsncmp.c ../include/wchar.h ../include/sys/types.h
wcsncpy.o: wcsncpy.c ../include/wchar.h ../include/sys/types.h
wcsnicmp.o: wcsnicmp.c ../include/wchar.h ../include/sys/types.h
wcspbrk.o: wcspbrk.c ../include/string.h ../include/sys/types.h
wcsrchr.o: wcsrchr.c ../include/string.h ../include/sys/types.h
wcstombs.o: wcstombs.c ../include/wchar.h ../include/sys/types.h \
  ../include/errno.h
wcwidth.o: wcwidth.c ../include/wchar.h ../include/sys/types.h
djmd.o: djmd.S
djmdr.o: djmdr.S
memcpy.o: memcpy.S
memmove.o: memmove.S
memset.o: memset.S
